### ISSUE TITLE
run_tests.sh fails in CI from `cfssl` being the default 

### ISSUE THREAD

**Issue by lukehinds** [keylime/python-keylime#21]
# Environment
 * OS / version: Fedora 28
 * Processor architecture: container
 * TPM Manufacturer: N/A
 * Keylime version: master

# Description 

With the default `keylime.conf` available in the root directory of the project, the `ca_implementation` value is set to `cfssl`. cfssl requires some extras (setting go path, grabbing cfssl module), unlike `openssl`, so run_tests.sh will stall from waiting for cfssl to start:

```
==================================================================================
			Begin Testing Phase
==================================================================================
Using config file /etc/keylime.conf
test.test_ca_impl_openssl
  OpenSSL_Test
.   test_openssl
test.test_crypto
  Crypto_Test
.   test_aes
.   test_errors
.   test_hmac
.   test_rsaTPM Initializing...
.   test_rsa_sign
.   test_xor
test.test_kl_sqlite
  Sqlite_Test
.   test_sql
DONE

Cloud Verifier Thread
Using config file /etc/keylime.conf
1546854681.74 - keylime.cloudverifier - INFO - Starting Cloud Verifier (tornado) on port 8881, use <Ctrl-C> to stop
1546854681.74 - keylime.cloudverifier_common - INFO - Setting up TLS...
1546854681.74 - keylime.cloudverifier_common - INFO - Generating a new CA in /var/lib/keylime/cv_ca and a client certificate for connecting
1546854681.74 - keylime.cloudverifier_common - INFO - use keylime_ca -d /var/lib/keylime/cv_ca to manage this CA
1546854681.74 - keylime.cloudverifier_common - WARNING - CAUTION: using default password for CA, please set private_key_pw to a strong password
1546854681.75 - keylime.ca_impl_cfssl - DEBUG - Waiting for cfssl to start...
Registrar Thread
Using config file /etc/keylime.conf
1546854711.7 - keylime.cloudverifier_common - INFO - Setting up TLS...
1546854711.7 - keylime.registrar - ERROR - It appears that the verifier has not yet created a CA and certificates, please run the verifier first
Traceback (most recent call last):
  File "/root/python-keylime/test/../keylime//registrar.py", line 38, in <module>
    main()
  File "/root/python-keylime/test/../keylime//registrar.py", line 34, in main
    registrar_common.start(config.getint('general', 'registrar_tls_port'),config.getint('general', 'registrar_port'),config.get('registrar', 'db_filename'))
  File "/root/python-keylime/keylime/registrar_common.py", line 422, in start
    generatedir='reg_ca')
  File "/root/python-keylime/keylime/cloud_verifier_common.py", line 128, in init_mtls
    raise Exception("It appears that the verifier has not yet created a CA and certificates, please run the verifier first")
Exception: It appears that the verifier has not yet created a CA and certificates, please run the verifier first
```

My recommendation is that we amend `run-tests.sh` to add an extra argument that can be passed:

```
-c 		 Run Coverage scans
-u 		 Run in user (non-root) mode
-h 		 This help info
-ca            ( cfssl | openssl)
```
Choosing either option results in `sed` setting the preferred `ca_implementation` in `/etc/keylime.conf`, and for `cfssl` the extra setup of golang and the cfssl module is performed.

This way we can have test coverage of both cfssl and openssl (we can run two builds in gate to test both CA variants).

**Comment by lukehinds** [comment]
https://github.com/mit-ll/python-keylime/pull/23

**Comment by lukehinds** [comment]
I still need to work on cfssl a bit more, but this change allows me to get on with #9  by using openssl to start things off.
